version: 3

dotenv: ['.env']

vars:
  MIGRATIONS_DIR: "./migrations"


tasks:
  generate-auth-proto:
    cmds:
      - protoc -I api/proto --go_out=pkg/proto/gen --go_opt=paths=source_relative --go-grpc_out=pkg/proto/gen --go-grpc_opt=paths=source_relative --grpc-gateway_out=pkg/proto/gen --grpc-gateway_opt=paths=source_relative api/proto/auth/v1/auth.proto 
    desc: Generate Go code from .proto files
  
  create-migration:
    desc: Create a new SQL migration with the given name
    cmds:
      - goose -dir {{.MIGRATIONS_DIR}} create {{.CLI_ARGS}} sql 
    